!!org.myrobotlab.service.config.RuntimeConfig
registry:
- runtime
- i01
- i01.left
- i01.left.serial
- i01.leftHand
- i01.leftHand.thumb
- i01.leftHand.index
- i01.leftHand.majeure
- i01.leftHand.ringFinger
- i01.leftHand.pinky
- i01.leftHand.wrist
type: Runtime
#virtual: true
