!!org.myrobotlab.service.config.ServoConfig
controller: i01.left
autoDisable: true
clip: true
enabled: false
idleTimeout: 3000
inverted: false
maxIn: 120.0
maxOut: 120.0
minIn: 60.0
minOut: 60.0
pin: '24'
rest: 90.0
speed: null
sweepMax: null
sweepMin: null
type: Servo
