!!org.myrobotlab.service.config.ServoConfig
autoDisable: true
clip: true
controller: i01.left
enabled: false
idleTimeout: 3000
inverted: false
maxIn: 25.0
maxOut: 25.0
minIn: 10.0
minOut: 10.0
pin: '26'
rest: 10.0
speed: 100.0
sweepMax: null
sweepMin: null
type: Servo
