!!org.myrobotlab.service.config.ServoConfig
autoDisable: true
clip: true
enabled: false
idleTimeout: 3000
inverted: false
maxIn: 180.0
maxOut: 180.0
minIn: 0.0
minOut: 0.0
pin: '10'
rest: 30.0
speed: 20.0
sweepMax: null
sweepMin: null
type: Servo
