!!org.myrobotlab.service.config.RuntimeConfig
attach:
- i01
- i01.rightArm.bicep
- i01.rightArm.omoplate
- i01.rightArm.rotate
- i01.rightArm.shoulder
- i01.rightHand.index
- i01.rightHand.majeure
- i01.rightHand.pinky
- i01.rightHand.ringFinger
- i01.rightHand.thumb
- i01.rightHand.wrist
- i01.simulator
locale: en-US
name: runtime
registry:
- runtime
- i01
- i01.rightHand
- i01.rightHand.thumb
- i01.rightHand.index
- i01.rightHand.majeure
- i01.rightHand.ringFinger
- i01.rightHand.pinky
- i01.rightHand.wrist
- i01.rightArm
- i01.rightArm.bicep
- i01.rightArm.omoplate
- i01.rightArm.rotate
- i01.rightArm.shoulder
- i01.simulator
- i01.right
- i01.right.serial
- i01.mouth
- i01.mouth.audioFile
- i01.ear
- i01.chatBot
- i01.chatBot.search
- i01.htmlFilter
type: Runtime
