!!org.myrobotlab.service.config.ServoConfig
autoDisable: true
clip: true
controller: i01.left
enabled: false
idleTimeout: 3000
inverted: false
maxIn: 160.0
maxOut: 160.0
minIn: 20.0
minOut: 20.0
peers: null
pin: '12'
rest: 90.0
speed: 45.0
sweepMax: null
sweepMin: null
synced: null
type: Servo
