!!org.myrobotlab.service.config.RuntimeConfig
locale: en-US
registry:
- runtime
- i01
- i01.mouth
- i01.ear
- i01.chatBot
- i01.htmlFilter
- i01.head
- i01.head.jaw
- i01.head.eyeX
- i01.head.eyeY
- i01.head.rothead
- i01.head.neck
- i01.head.rollNeck
- i01.head.eyelidLeft
- i01.head.eyelidRight
- i01.mouthControl
- i01.opencv
- i01.right
- i01.right.serial
- i01.left
- i01.left.serial
type: Runtime
virtual: false
