!!org.myrobotlab.service.config.ServoConfig
autoDisable: true
clip: true
controller: i01.left
enabled: false
idleTimeout: 3000
inverted: false
maxIn: 180.0
maxOut: 180.0
minIn: 0.0
minOut: 0.0
pin: '28'
rest: 90.0
speed: 5.0
sweepMax: null
sweepMin: null
type: Servo
